pipeline {
    agent any

    stages {

        stage('build') {
            
            steps {
                sh "echo 'building the app'"
            }
        }
        stage('test') {
            
            steps {
                sh "echo 'testing the app'"
            }
        }
        stage('deploy') {
            
            steps {
                sh "echo 'deploying the app'"
            }
        }
    }
}